### ISSUE TITLE
Please make the plugin multilingual

### ISSUE THREAD

**Issue by pcav** [jorgealmerio/QEsg#3]
So it will be easier for others to contribute with localization in other languages, and with coding.
This involves both strings (see one of the multilingual plugins for an example, using standard tools), and (less obvious) name of the variables: it is generally advisable to use English names, to allow more people to understand it.

**Comment by jorgealmerio** [comment]
I have already translated the strings from Portuguese to English, using the Qt Linguist tool.
As for the variables, taking into account the care that must be taken in translating them to avoid code errors, I shall do it on a future version.
I thank you in advance for approving thist version of my plugin as it is.

Best Regards,
Jorge Almerio

**Comment by jorgealmerio** [comment]
Thanks for approvation.
By the way, Do I need to upload the updated zipped file with the bugtracker fixed to http://plugins.qgis.org/plugin or it will automatically commited from my github code repository?

**Comment by pcav** [comment]
You have to upload it manually.
Thanks.
