### ISSUE TITLE
classFactory module error

### ISSUE THREAD

**Issue by PappyEric** [jorgealmerio/QEsg#4]
I have this plugin and use it in QGIS 2.x , and saw it may be ready for 3.x (if not then please ignore this issue and I'll wait until it's ready).

![screen shot 2019-01-14 at 4 28 42 pm](https://user-images.githubusercontent.com/18177830/51142348-ac91dc00-1819-11e9-83fc-13a2510fc788.png)

I get the above error when installing QEsg then again if I don't un-install once opening QGIS again.

I have both QGIS 2.x and 3.x if that's a problem. But maybe I'm missing something easy.

**Comment by jorgealmerio** [comment]
Yes, you are right, There is a QEsg version for Qgis 3 !
But you have to install matplotlib for python 3 !
If you used the OSGeo install, just update installation by adding the matplotlib for python 3.

**Comment by PappyEric** [comment]
I'm on a Mac here so having some difficulties installing a working version of matplot. I'm not finding a Mac version of OSgeo.

**Comment by PappyEric** [comment]
I'm also finding others having the same issues with GDAL/OSGeo and matplot on Mac.  Any help would be appreciated but I also understand that if you don't have a Mac you may not be able to trouble shoot my issue.
