### ISSUE TITLE
minimim covering

### ISSUE THREAD

**Issue by trasto21** [jorgealmerio/QEsg#6]
i'm using your plugin and is wonderful. the only issue i found were impossible modify the minimim covering, even if i change the number in the settings mask

**Comment by jorgealmerio** [comment]
The minimum covering in the settings is the default value for covering. It's only used the first time you ask the plugin to fill in data with default values. The covering may be changed in the 'REC_MIN' attribute table field for each pipe reach (each record in the table).

**Comment by trasto21** [comment]
ok, thanks, i have a solution as you told me.  anyway, the slot in the setting mask don't change the coloumn in the pipes' database.

**Comment by jorgealmerio** [comment]
You are right, maybe the label "Default Minimum covering (m)" would be more appropriated!
I think it's NOT a good idea to change all the columns values from the "setting mask", because you can have particular covering already manual entered in the attribute table. What do you think?

**Comment by trasto21** [comment]
the value in the setting mask don't update the coloumn and should be a good
first step for the implementation of that coloumn. then you can change
every value in the database for the particular covering manual entered

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno lun 8 lug 2019 alle ore 22:07 jorgealmerio <
notifications@github.com> ha scritto:

**Comment by jorgealmerio** [comment]
No, you are wrong!
If you have 'REC_MIN' Column with Null values (First time) and use the '04 Fill Fields' <img src="https://user-images.githubusercontent.com/16169268/60885988-3483fc00-a227-11e9-86dd-e456f0090e14.png" width=25px/>
 button command, so the column will be filled in with the 'setting mask'!

I think I will put a button beside the setting mask to overwrite the column.
