### ISSUE TITLE
04 Preencher os campos - Erro Phyton

### ISSUE THREAD

**Issue by FCamargo84** [jorgealmerio/QEsg#8]
![erro](https://github.com/user-attachments/assets/baea47fa-da26-4ea9-9f79-769d0b865113)
Olá!
Estou tendo problema para identificar esse erro e corrigir no meu projeto.
Você pode me ajudar por favor?

Obrigado
Fabrício

**Comment by jorgealmerio** [comment]
Please update 'QEsg' to version 3.2.4!
Let me know if it's fixed!

**Comment by FCamargo84** [comment]
Thank you very much Jorge!!
worked like a charm 👍
